In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [2]:
TrainVal_scaled = pd.read_csv('01train_scaled.csv', index_col=0, parse_dates=True)
Test_scaled     = pd.read_csv('01test_scaled.csv', index_col=0, parse_dates=True)
Ext = TrainVal_scaled[:4320]

In [3]:
TrainVal_scaled

f1        f2        f3        f4        f5  \
Timestamp                                                               
2017-08-17 00:00:00  0.162602  0.108504  0.086842  0.179612  0.169811   
2017-08-17 00:05:00  0.126016  0.105572  0.105061  0.160194  0.156334   
2017-08-17 00:10:00  0.158537  0.123167  0.076923  0.153722  0.159030   
2017-08-17 00:15:00  0.130081  0.099707  0.071255  0.160194  0.177898   
2017-08-17 00:20:00  0.121951  0.085044  0.058704  0.135922  0.159030   
...                       ...       ...       ...       ...       ...   
2018-02-18 23:35:00  0.207317  0.170088  0.141700  0.160194  0.097035   
2018-02-18 23:40:00  0.117886  0.090909  0.147773  0.139159  0.083558   
2018-02-18 23:45:00  0.150407  0.108504  0.133603  0.179612  0.102426   
2018-02-18 23:50:00  0.142276  0.114370  0.119433  0.171521  0.113208   
2018-02-18 23:55:00  0.138211  0.099707  0.113360  0.171521  0.110512   

                           f6  
Timestamp                      
2017-08-17 00:00:00  0.239437  
2017-08-17 00:05:00  0.247887  
2017-08-17 00:10:00  0.239437  
2017-08-17 00:15:00  0.281690  
2017-08-17 00:20:00  0.256338  
...                       ...  
2018-02-18 23:35:00  0.008451  
2018-02-18 23:40:00  0.081690  
2018-02-18 23:45:00  0.019718  
2018-02-18 23:50:00  0.030986  
2018-02-18 23:55:00  0.008451  

[53568 rows x 6 columns]

In [4]:
Test_scaled

f1        f2        f3        f4        f5  \
Timestamp                                                               
2018-02-19 00:00:00  0.154472  0.123167  0.113360  0.139159  0.091644   
2018-02-19 00:05:00  0.126016  0.093842  0.101215  0.114887  0.078167   
2018-02-19 00:10:00  0.109756  0.105572  0.074899  0.144013  0.099730   
2018-02-19 00:15:00  0.121951  0.073314  0.082996  0.116505  0.072776   
2018-02-19 00:20:00  0.138211  0.096774  0.113360  0.161812  0.110512   
...                       ...       ...       ...       ...       ...   
2018-03-04 23:35:00  0.162602  0.117302  0.139676  0.174757  0.167116   
2018-03-04 23:40:00  0.134146  0.105572  0.105263  0.134304  0.110512   
2018-03-04 23:45:00  0.170732  0.155425  0.089069  0.135922  0.099730   
2018-03-04 23:50:00  0.150407  0.123167  0.113360  0.165049  0.099730   
2018-03-04 23:55:00  0.162602  0.108504  0.115385  0.142395  0.107817   

                           f6  
Timestamp                      
2018-02-19 00:00:00  0.008451  
2018-02-19 00:05:00  0.008451  
2018-02-19 00:10:00  0.008451  
2018-02-19 00:15:00  0.008451  
2018-02-19 00:20:00  0.008451  
...                       ...  
2018-03-04 23:35:00  0.140845  
2018-03-04 23:40:00  0.073239  
2018-03-04 23:45:00  0.039437  
2018-03-04 23:50:00  0.025352  
2018-03-04 23:55:00  0.028169  

[4032 rows x 6 columns]

### Total Data

In [5]:
df = pd.concat([TrainVal_scaled, Test_scaled])

In [6]:
df

f1        f2        f3        f4        f5  \
Timestamp                                                               
2017-08-17 00:00:00  0.162602  0.108504  0.086842  0.179612  0.169811   
2017-08-17 00:05:00  0.126016  0.105572  0.105061  0.160194  0.156334   
2017-08-17 00:10:00  0.158537  0.123167  0.076923  0.153722  0.159030   
2017-08-17 00:15:00  0.130081  0.099707  0.071255  0.160194  0.177898   
2017-08-17 00:20:00  0.121951  0.085044  0.058704  0.135922  0.159030   
...                       ...       ...       ...       ...       ...   
2018-03-04 23:35:00  0.162602  0.117302  0.139676  0.174757  0.167116   
2018-03-04 23:40:00  0.134146  0.105572  0.105263  0.134304  0.110512   
2018-03-04 23:45:00  0.170732  0.155425  0.089069  0.135922  0.099730   
2018-03-04 23:50:00  0.150407  0.123167  0.113360  0.165049  0.099730   
2018-03-04 23:55:00  0.162602  0.108504  0.115385  0.142395  0.107817   

                           f6  
Timestamp                      
2017-08-17 00:00:00  0.239437  
2017-08-17 00:05:00  0.247887  
2017-08-17 00:10:00  0.239437  
2017-08-17 00:15:00  0.281690  
2017-08-17 00:20:00  0.256338  
...                       ...  
2018-03-04 23:35:00  0.140845  
2018-03-04 23:40:00  0.073239  
2018-03-04 23:45:00  0.039437  
2018-03-04 23:50:00  0.025352  
2018-03-04 23:55:00  0.028169  

[57600 rows x 6 columns]

In [7]:
df.drop(columns = ['f1', 'f2', 'f3', 'f5', 'f6'], inplace=True);

In [8]:
df

f4
Timestamp                    
2017-08-17 00:00:00  0.179612
2017-08-17 00:05:00  0.160194
2017-08-17 00:10:00  0.153722
2017-08-17 00:15:00  0.160194
2017-08-17 00:20:00  0.135922
...                       ...
2018-03-04 23:35:00  0.174757
2018-03-04 23:40:00  0.134304
2018-03-04 23:45:00  0.135922
2018-03-04 23:50:00  0.165049
2018-03-04 23:55:00  0.142395

[57600 rows x 1 columns]

In [9]:
df.iloc[4320]          # First sample

f4    0.250809
Name: 2017-09-01 00:00:00, dtype: float64

In [10]:
df.iloc[2304]          # -1 week (-2016 samples)

f4    0.179612
Name: 2017-08-25 00:00:00, dtype: float64

In [11]:
df.iloc[288]          # -2 week (-4032 samples)

f4    0.195793
Name: 2017-08-18 00:00:00, dtype: float64

# Generate Weekly Samples

In [12]:
a = np.zeros((2, 7))
b = np.zeros((2, 7))
x = 4320                           # Start

for i in range(len(df.iloc[x:])):
    for j in range(2):
        for k in range(7):
            if j == 0:
                a[j][k] = df.iloc[x-2019+i+k]
            else:
                a[j][k] = df.iloc[x-4035+i+k]
    b = np.append(b, a, axis=0)

b = np.delete(b, np.s_[0:2], 0).reshape(-1, 2, 7)

In [13]:
b[0]

array([[0.22491909, 0.15857605, 0.24919094, 0.17961165, 0.22815534,
        0.17799353, 0.11326861],
       [0.17799353, 0.14724919, 0.16343042, 0.19579288, 0.17961165,
        0.197411  , 0.16019417]])

In [14]:
b[1]

array([[0.15857605, 0.24919094, 0.17961165, 0.22815534, 0.17799353,
        0.11326861, 0.13268608],
       [0.14724919, 0.16343042, 0.19579288, 0.17961165, 0.197411  ,
        0.16019417, 0.16666667]])

In [15]:
b[0].flatten()

array([0.22491909, 0.15857605, 0.24919094, 0.17961165, 0.22815534,
       0.17799353, 0.11326861, 0.17799353, 0.14724919, 0.16343042,
       0.19579288, 0.17961165, 0.197411  , 0.16019417])

In [16]:
a = b.flatten().reshape(-1,14)

In [17]:
a[0]

array([0.22491909, 0.15857605, 0.24919094, 0.17961165, 0.22815534,
       0.17799353, 0.11326861, 0.17799353, 0.14724919, 0.16343042,
       0.19579288, 0.17961165, 0.197411  , 0.16019417])

In [18]:
len(a) == len(TrainVal_scaled) + len(Test_scaled) - len(Ext)

True

### Split into corresponding test and train

In [19]:
a.shape

(53280, 14)

In [20]:
Ext.shape[0]

4320

In [21]:
TrainVal_scaled[4320:].shape

(49248, 6)

In [22]:
train = a[:TrainVal_scaled[4320:].shape[0]]

In [23]:
train.shape

(49248, 14)

In [24]:
test = a[TrainVal_scaled[4320:].shape[0]:]

In [25]:
test.shape

(4032, 14)

In [26]:
Test_scaled.shape

(4032, 6)

#### Confirmation

In [27]:
test[0]

array([0.0987055 , 0.16343042, 0.13754045, 0.0566343 , 0.12783172,
       0.1197411 , 0.0987055 , 0.11003236, 0.07605178, 0.06957929,
       0.11650485, 0.05339806, 0.09385113, 0.06634304])

In [28]:
TrainVal_scaled.iloc[-2016]['f4']  

0.0566343042071197

# Save Data

In [29]:
joblib.dump(train, "002weeks_train.save");
joblib.dump(test, "002weeks_test.save"); 