In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [2]:
Ext             = pd.DataFrame(joblib.load("0000Test.save")) 

In [3]:
columns = ['f1', 'f2', 'f3', 'f4', 'f5', 'f6']
Ext.columns = columns

In [4]:
Ext

f1        f2        f3        f4        f5        f6
0     0.227642  0.205279  0.253036  0.281553  0.221024  0.050704
1     0.203252  0.187683  0.194332  0.299353  0.226415  0.070423
2     0.174797  0.152493  0.230769  0.276699  0.194070  0.059155
3     0.182927  0.187683  0.163968  0.226537  0.140162  0.045070
4     0.186992  0.181818  0.163968  0.234628  0.180593  0.042254
...        ...       ...       ...       ...       ...       ...
8347  0.174797  0.167155  0.170040  0.211974  0.164420  0.104225
8348  0.203252  0.175953  0.165992  0.163430  0.164420  0.166197
8349  0.138211  0.123167  0.216599  0.231392  0.188679  0.064789
8350  0.158537  0.137830  0.206478  0.213592  0.196765  0.047887
8351  0.146341  0.120235  0.149798  0.153722  0.153639  0.143662

[8352 rows x 6 columns]

### Total Data

In [5]:
df = Ext.copy()

In [6]:
df

f1        f2        f3        f4        f5        f6
0     0.227642  0.205279  0.253036  0.281553  0.221024  0.050704
1     0.203252  0.187683  0.194332  0.299353  0.226415  0.070423
2     0.174797  0.152493  0.230769  0.276699  0.194070  0.059155
3     0.182927  0.187683  0.163968  0.226537  0.140162  0.045070
4     0.186992  0.181818  0.163968  0.234628  0.180593  0.042254
...        ...       ...       ...       ...       ...       ...
8347  0.174797  0.167155  0.170040  0.211974  0.164420  0.104225
8348  0.203252  0.175953  0.165992  0.163430  0.164420  0.166197
8349  0.138211  0.123167  0.216599  0.231392  0.188679  0.064789
8350  0.158537  0.137830  0.206478  0.213592  0.196765  0.047887
8351  0.146341  0.120235  0.149798  0.153722  0.153639  0.143662

[8352 rows x 6 columns]

In [7]:
date_range = pd.date_range('2018-07-01 00:00', '2018-07-29 23:59', freq='5Min')
myser = pd.Series(data=date_range, name='Timestamp')

In [8]:
len(myser)

8352

In [9]:
df.drop(columns = ['f1', 'f2', 'f3', 'f5', 'f6'], inplace=True);
df['Timestamp'] = myser

# Re-arrange spatial columns, so, the data is sequential
df = df[['Timestamp','f4']]

In [10]:
df

Timestamp        f4
0    2018-07-01 00:00:00  0.281553
1    2018-07-01 00:05:00  0.299353
2    2018-07-01 00:10:00  0.276699
3    2018-07-01 00:15:00  0.226537
4    2018-07-01 00:20:00  0.234628
...                  ...       ...
8347 2018-07-29 23:35:00  0.211974
8348 2018-07-29 23:40:00  0.163430
8349 2018-07-29 23:45:00  0.231392
8350 2018-07-29 23:50:00  0.213592
8351 2018-07-29 23:55:00  0.153722

[8352 rows x 2 columns]

In [11]:
df.iloc[4320]          # First sample

Timestamp    2018-07-16 00:00:00
f4                      0.169903
Name: 4320, dtype: object

In [12]:
df.iloc[2304]          # -1 week (-2016 samples)

Timestamp    2018-07-09 00:00:00
f4                      0.098706
Name: 2304, dtype: object

In [13]:
df.iloc[288]           # -2 week (-4032 samples)

Timestamp    2018-07-02 00:00:00
f4                      0.169903
Name: 288, dtype: object

# Generate Weekly Samples

In [14]:
a = np.zeros((2, 7))
b = np.zeros((2, 7))
x = 4320                           # Start

for i in range(len(df.iloc[x:])):
    for j in range(2):
        for k in range(7):
            if j == 0:
                a[j][k] = df.iloc[x-2019+i+k].drop(['Timestamp'])
            else:
                a[j][k] = df.iloc[x-4035+i+k].drop(['Timestamp'])
    b = np.append(b, a, axis=0)

b = np.delete(b, np.s_[0:2], 0).reshape(-1, 2, 7)

In [15]:
b[0]

array([[0.11003236, 0.11812298, 0.10517799, 0.0987055 , 0.09385113,
        0.0987055 , 0.07605178],
       [0.20550162, 0.20064725, 0.14563107, 0.16990291, 0.17961165,
        0.13754045, 0.20711974]])

In [16]:
b[1]

array([[0.11812298, 0.10517799, 0.0987055 , 0.09385113, 0.0987055 ,
        0.07605178, 0.0776699 ],
       [0.20064725, 0.14563107, 0.16990291, 0.17961165, 0.13754045,
        0.20711974, 0.13754045]])

In [17]:
b[0].flatten()

array([0.11003236, 0.11812298, 0.10517799, 0.0987055 , 0.09385113,
       0.0987055 , 0.07605178, 0.20550162, 0.20064725, 0.14563107,
       0.16990291, 0.17961165, 0.13754045, 0.20711974])

In [18]:
a = b.flatten().reshape(-1,14)

In [19]:
a[0]

array([0.11003236, 0.11812298, 0.10517799, 0.0987055 , 0.09385113,
       0.0987055 , 0.07605178, 0.20550162, 0.20064725, 0.14563107,
       0.16990291, 0.17961165, 0.13754045, 0.20711974])

#### Confirmation

In [20]:
a[0]

array([0.11003236, 0.11812298, 0.10517799, 0.0987055 , 0.09385113,
       0.0987055 , 0.07605178, 0.20550162, 0.20064725, 0.14563107,
       0.16990291, 0.17961165, 0.13754045, 0.20711974])

In [21]:
df.iloc[2304] 

Timestamp    2018-07-09 00:00:00
f4                      0.098706
Name: 2304, dtype: object

In [22]:
df.iloc[288] 

Timestamp    2018-07-02 00:00:00
f4                      0.169903
Name: 288, dtype: object

In [23]:
len(a)

4032

# Save Data

In [24]:
joblib.dump(a, "002weeks_test_July.save"); 