In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [2]:
# General Period
test_period = joblib.load("00Periodicity_test.save") 

# 2 Week priodicity
test_2week = joblib.load("002weeks_test_Nov.save") 

In [3]:
test_period.shape

(4032, 49)

In [4]:
test_2week.shape

(4032, 14)

In [5]:
test_period[0]

array([0.16713122, 0.03651526, 0.11320755, 0.25728988, 0.14451115,
       0.15951973, 0.19554031, 0.16863208, 0.02200822, 0.11663808,
       0.21783877, 0.15608919, 0.16723842, 0.18524871, 0.14633362,
       0.0290194 , 0.11320755, 0.22298456, 0.12735849, 0.13979417,
       0.15866209, 0.1292167 , 0.02506424, 0.08747856, 0.17495712,
       0.11320755, 0.13036021, 0.14493997, 0.13859348, 0.01836216,
       0.11492281, 0.17324185, 0.12349914, 0.13379074, 0.15265866,
       0.13127501, 0.03156054, 0.06174957, 0.2058319 , 0.11749571,
       0.13379074, 0.13979417, 0.12795883, 0.02422111, 0.10806175,
       0.20926244, 0.11578045, 0.12349914, 0.12950257])

In [6]:
test_2week[0]

array([0.13379074, 0.12864494, 0.11492281, 0.12521441, 0.10634648,
       0.12521441, 0.10291595, 0.15780446, 0.10291595, 0.10977702,
       0.10291595, 0.08404803, 0.09777015, 0.11149228])

In [7]:
np.concatenate((test_period[0], test_2week[0]), axis=0)

array([0.16713122, 0.03651526, 0.11320755, 0.25728988, 0.14451115,
       0.15951973, 0.19554031, 0.16863208, 0.02200822, 0.11663808,
       0.21783877, 0.15608919, 0.16723842, 0.18524871, 0.14633362,
       0.0290194 , 0.11320755, 0.22298456, 0.12735849, 0.13979417,
       0.15866209, 0.1292167 , 0.02506424, 0.08747856, 0.17495712,
       0.11320755, 0.13036021, 0.14493997, 0.13859348, 0.01836216,
       0.11492281, 0.17324185, 0.12349914, 0.13379074, 0.15265866,
       0.13127501, 0.03156054, 0.06174957, 0.2058319 , 0.11749571,
       0.13379074, 0.13979417, 0.12795883, 0.02422111, 0.10806175,
       0.20926244, 0.11578045, 0.12349914, 0.12950257, 0.13379074,
       0.12864494, 0.11492281, 0.12521441, 0.10634648, 0.12521441,
       0.10291595, 0.15780446, 0.10291595, 0.10977702, 0.10291595,
       0.08404803, 0.09777015, 0.11149228])

### Concatenation

In [8]:
b = np.zeros(63)

for i in range(len(test_period)):
    a = np.concatenate((test_period[i], test_2week[i]), axis=0)
    b = np.append(b, a, axis=0)
    
b = b.reshape(-1,63)
Xtest = np.delete(b, np.s_[0], 0)

In [9]:
Xtest[0] == np.concatenate((test_period[0], test_2week[0]), axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [10]:
Xtest.shape

(4032, 63)

# Samples

### 5 mins

In [11]:
# Delete first 15 samples
a = np.delete(Xtest, np.s_[0:15], 0)

In [12]:
len(a)

4017

In [13]:
# Save 

np.save("Wide_test_Nov_5", a)

### 15 mins

In [14]:
# Delete first 15 samples
a = np.delete(Xtest, np.s_[0:17], 0)

In [15]:
len(a)

4015

In [16]:
# Save 

np.save("Wide_test_Nov_15", a)

### 30 mins

In [17]:
# Delete first 15 samples
a = np.delete(Xtest, np.s_[0:20], 0)

In [18]:
len(a)

4012

In [19]:
# Save 

np.save("Wide_test_Nov_30", a)

### 60 mins

In [20]:
# Delete first 15 samples
a = np.delete(Xtest, np.s_[0:26], 0)

In [21]:
len(a)

4006

In [22]:
# Save 

np.save("Wide_test_Nov_60", a)