In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [2]:
Ext             = pd.DataFrame(joblib.load("Extension.save"))
TrainVal_scaled = pd.read_csv('01train_scaled.csv').drop(['Timestamp','Unnamed: 0'], axis=1)
Test_scaled     = pd.read_csv('01test_scaled.csv').drop(['Timestamp','Unnamed: 0'], axis=1)

In [3]:
columns = ['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7']
Ext.columns = columns

In [4]:
Ext

f1        f2        f3        f4        f5        f6        f7
0     0.167038  0.147773  0.147170  0.185106  0.114923  0.089015  0.130435
1     0.162584  0.165992  0.216981  0.206383  0.144082  0.102273  0.165217
2     0.164811  0.137652  0.162264  0.210638  0.150943  0.109848  0.163043
3     0.151448  0.125506  0.149057  0.182979  0.118353  0.068182  0.113043
4     0.093541  0.121457  0.139623  0.200000  0.102916  0.075758  0.121739
...        ...       ...       ...       ...       ...       ...       ...
4315  0.213808  0.186235  0.143396  0.189362  0.144082  0.151515  0.136957
4316  0.271715  0.202429  0.226415  0.225532  0.149228  0.132576  0.136957
4317  0.220490  0.180162  0.215094  0.204255  0.162950  0.153409  0.167391
4318  0.213808  0.194332  0.233962  0.231915  0.156089  0.121212  0.147826
4319  0.195991  0.200405  0.200000  0.253191  0.169811  0.098485  0.115217

[4320 rows x 7 columns]

In [5]:
TrainVal_scaled

f1        f2        f3        f4        f5        f6        f7
0      0.200445  0.161943  0.230189  0.265957  0.190395  0.060606  0.084783
1      0.191537  0.155870  0.235849  0.265957  0.174957  0.125000  0.154348
2      0.213808  0.214575  0.230189  0.238298  0.173242  0.126894  0.145652
3      0.213808  0.170040  0.175472  0.212766  0.152659  0.155303  0.182609
4      0.193764  0.161943  0.201887  0.242553  0.157804  0.113636  0.121739
...         ...       ...       ...       ...       ...       ...       ...
31099  0.298441  0.253036  0.288679  0.291489  0.255575  0.204545  0.184783
31100  0.407572  0.382591  0.358491  0.312766  0.286449  0.195076  0.191304
31101  0.276169  0.285425  0.309434  0.293617  0.257290  0.231061  0.247826
31102  0.271715  0.246964  0.335849  0.270213  0.217839  0.159091  0.173913
31103  0.229399  0.212551  0.245283  0.265957  0.222985  0.176136  0.189130

[31104 rows x 7 columns]

In [6]:
Test_scaled

f1        f2        f3        f4        f5        f6        f7
0     0.289532  0.277328  0.226415  0.259574  0.204117  0.147727  0.150000
1     0.258352  0.230769  0.277358  0.231915  0.198971  0.168561  0.160870
2     0.211581  0.208502  0.232075  0.242553  0.202401  0.195076  0.213043
3     0.242762  0.232794  0.213208  0.221277  0.176672  0.178030  0.195652
4     0.238307  0.226721  0.235849  0.253191  0.192110  0.126894  0.128261
...        ...       ...       ...       ...       ...       ...       ...
4027  0.282851  0.253036  0.264151  0.302128  0.233276  0.196970  0.169565
4028  0.262806  0.222672  0.243396  0.246809  0.166381  0.174242  0.180435
4029  0.204900  0.188259  0.213208  0.270213  0.221269  0.166667  0.171739
4030  0.273942  0.246964  0.247170  0.219149  0.183533  0.195076  0.193478
4031  0.247216  0.194332  0.237736  0.272340  0.193825  0.178030  0.200000

[4032 rows x 7 columns]

### Total Data

In [7]:
df = pd.concat([Ext, TrainVal_scaled, Test_scaled], ignore_index=True)

In [8]:
df

f1        f2        f3        f4        f5        f6        f7
0      0.167038  0.147773  0.147170  0.185106  0.114923  0.089015  0.130435
1      0.162584  0.165992  0.216981  0.206383  0.144082  0.102273  0.165217
2      0.164811  0.137652  0.162264  0.210638  0.150943  0.109848  0.163043
3      0.151448  0.125506  0.149057  0.182979  0.118353  0.068182  0.113043
4      0.093541  0.121457  0.139623  0.200000  0.102916  0.075758  0.121739
...         ...       ...       ...       ...       ...       ...       ...
39451  0.282851  0.253036  0.264151  0.302128  0.233276  0.196970  0.169565
39452  0.262806  0.222672  0.243396  0.246809  0.166381  0.174242  0.180435
39453  0.204900  0.188259  0.213208  0.270213  0.221269  0.166667  0.171739
39454  0.273942  0.246964  0.247170  0.219149  0.183533  0.195076  0.193478
39455  0.247216  0.194332  0.237736  0.272340  0.193825  0.178030  0.200000

[39456 rows x 7 columns]

In [9]:
date_range = pd.date_range('2019-02-14 00:00', '2019-06-30 23:59', freq='5Min')
myser = pd.Series(data=date_range, name='Timestamp')

In [10]:
len(myser)

39456

In [11]:
df['Timestamp'] = myser

# Re-arrange spatial columns, so, the data is sequential
df = df[['Timestamp','f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7']]

In [12]:
df

Timestamp        f1        f2        f3        f4        f5  \
0     2019-02-14 00:00:00  0.167038  0.147773  0.147170  0.185106  0.114923   
1     2019-02-14 00:05:00  0.162584  0.165992  0.216981  0.206383  0.144082   
2     2019-02-14 00:10:00  0.164811  0.137652  0.162264  0.210638  0.150943   
3     2019-02-14 00:15:00  0.151448  0.125506  0.149057  0.182979  0.118353   
4     2019-02-14 00:20:00  0.093541  0.121457  0.139623  0.200000  0.102916   
...                   ...       ...       ...       ...       ...       ...   
39451 2019-06-30 23:35:00  0.282851  0.253036  0.264151  0.302128  0.233276   
39452 2019-06-30 23:40:00  0.262806  0.222672  0.243396  0.246809  0.166381   
39453 2019-06-30 23:45:00  0.204900  0.188259  0.213208  0.270213  0.221269   
39454 2019-06-30 23:50:00  0.273942  0.246964  0.247170  0.219149  0.183533   
39455 2019-06-30 23:55:00  0.247216  0.194332  0.237736  0.272340  0.193825   

             f6        f7  
0      0.089015  0.130435  
1      0.102273  0.165217  
2      0.109848  0.163043  
3      0.068182  0.113043  
4      0.075758  0.121739  
...         ...       ...  
39451  0.196970  0.169565  
39452  0.174242  0.180435  
39453  0.166667  0.171739  
39454  0.195076  0.193478  
39455  0.178030  0.200000  

[39456 rows x 8 columns]

In [13]:
df.iloc[4320]          # First sample

Timestamp    2019-03-01 00:00:00
f1                      0.200445
f2                      0.161943
f3                      0.230189
f4                      0.265957
f5                      0.190395
f6                      0.060606
f7                      0.084783
Name: 4320, dtype: object

In [14]:
df.iloc[2304]          # -1 week (-2016 samples)

Timestamp    2019-02-22 00:00:00
f1                      0.202673
f2                      0.182186
f3                      0.239623
f4                      0.219149
f5                      0.164666
f6                       0.13447
f7                       0.13913
Name: 2304, dtype: object

In [15]:
df.iloc[288]          # -2 week (-4032 samples)

Timestamp    2019-02-15 00:00:00
f1                      0.158129
f2                      0.137652
f3                      0.162264
f4                      0.210638
f5                      0.157804
f6                      0.140152
f7                      0.132609
Name: 288, dtype: object

# Generate Weekly Samples

In [16]:
a = np.zeros((1, 9, 7))
b = np.zeros((1, 9, 7))
x = 4320                           # Start

for i in range(len(df.iloc[x:])):
    for j in range(9):
        a[0][j] = df.iloc[x-2020+i+j].drop(['Timestamp'])
        
    b = np.append(b, a, axis=0)

b = np.delete(b, np.s_[0:1], 0)

In [17]:
b[0]

array([[0.22939866, 0.21659919, 0.18301887, 0.25531915, 0.18181818,
        0.10795455, 0.11304348],
       [0.24498886, 0.22267206, 0.22641509, 0.21276596, 0.135506  ,
        0.13068182, 0.13695652],
       [0.24053452, 0.24291498, 0.19622642, 0.19574468, 0.1457976 ,
        0.14583333, 0.11956522],
       [0.19599109, 0.18218623, 0.23396226, 0.24680851, 0.18867925,
        0.13636364, 0.11304348],
       [0.20267261, 0.18218623, 0.23962264, 0.21914894, 0.16466552,
        0.1344697 , 0.13913043],
       [0.21158129, 0.17206478, 0.20943396, 0.23617021, 0.16638079,
        0.17045455, 0.14130435],
       [0.23608018, 0.23076923, 0.25849057, 0.21489362, 0.15608919,
        0.13068182, 0.11304348],
       [0.20267261, 0.17813765, 0.21886792, 0.25531915, 0.18010292,
        0.10795455, 0.14347826],
       [0.13363029, 0.12955466, 0.13207547, 0.18085106, 0.10291595,
        0.10416667, 0.11086957]])

In [18]:
b[1]

array([[0.24498886, 0.22267206, 0.22641509, 0.21276596, 0.135506  ,
        0.13068182, 0.13695652],
       [0.24053452, 0.24291498, 0.19622642, 0.19574468, 0.1457976 ,
        0.14583333, 0.11956522],
       [0.19599109, 0.18218623, 0.23396226, 0.24680851, 0.18867925,
        0.13636364, 0.11304348],
       [0.20267261, 0.18218623, 0.23962264, 0.21914894, 0.16466552,
        0.1344697 , 0.13913043],
       [0.21158129, 0.17206478, 0.20943396, 0.23617021, 0.16638079,
        0.17045455, 0.14130435],
       [0.23608018, 0.23076923, 0.25849057, 0.21489362, 0.15608919,
        0.13068182, 0.11304348],
       [0.20267261, 0.17813765, 0.21886792, 0.25531915, 0.18010292,
        0.10795455, 0.14347826],
       [0.13363029, 0.12955466, 0.13207547, 0.18085106, 0.10291595,
        0.10416667, 0.11086957],
       [0.16035635, 0.12550607, 0.1509434 , 0.1893617 , 0.12349914,
        0.07575758, 0.07173913]])

In [19]:
b.shape

(35136, 9, 7)

### Split into corresponding test and train

In [20]:
train = b[:TrainVal_scaled.shape[0]]

In [21]:
train.shape

(31104, 9, 7)

In [22]:
TrainVal_scaled.shape

(31104, 7)

In [23]:
test = b[TrainVal_scaled.shape[0]:]

In [24]:
test.shape

(4032, 9, 7)

In [25]:
Test_scaled.shape

(4032, 7)

#### Confirmation

In [26]:
test[0][4]

array([0.18040089, 0.15384615, 0.19622642, 0.19148936, 0.12864494,
       0.09090909, 0.11956522])

In [27]:
TrainVal_scaled.iloc[-2016]

f1    0.180401
f2    0.153846
f3    0.196226
f4    0.191489
f5    0.128645
f6    0.090909
f7    0.119565
Name: 29088, dtype: float64

# Save Data

In [28]:
joblib.dump(train, "002weeks_train_Multi.save");
joblib.dump(test, "002weeks_test_Multi.save"); 