In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [2]:
Ext             = pd.DataFrame(joblib.load("0000Test.save")) 

In [3]:
columns = ['f1', 'f2', 'f3', 'f4', 'f5', 'f6', 'f7']
Ext.columns = columns

In [4]:
Ext

f1        f2        f3        f4        f5        f6        f7
0     0.236080  0.200405  0.228302  0.227660  0.156089  0.134470  0.147826
1     0.240535  0.206478  0.216981  0.285106  0.209262  0.166667  0.145652
2     0.184855  0.182186  0.156604  0.261702  0.185249  0.185606  0.191304
3     0.216036  0.212551  0.226415  0.242553  0.183533  0.136364  0.163043
4     0.204900  0.178138  0.205660  0.193617  0.123499  0.164773  0.169565
...        ...       ...       ...       ...       ...       ...       ...
8347  0.224944  0.216599  0.233962  0.242553  0.192110  0.172348  0.219565
8348  0.187082  0.125506  0.183019  0.229787  0.180103  0.193182  0.252174
8349  0.262806  0.218623  0.273585  0.246809  0.176672  0.147727  0.206522
8350  0.231626  0.224696  0.215094  0.217021  0.178388  0.151515  0.215217
8351  0.189310  0.161943  0.177358  0.212766  0.162950  0.181818  0.247826

[8352 rows x 7 columns]

### Total Data

In [5]:
df = Ext.copy()

In [6]:
df

f1        f2        f3        f4        f5        f6        f7
0     0.236080  0.200405  0.228302  0.227660  0.156089  0.134470  0.147826
1     0.240535  0.206478  0.216981  0.285106  0.209262  0.166667  0.145652
2     0.184855  0.182186  0.156604  0.261702  0.185249  0.185606  0.191304
3     0.216036  0.212551  0.226415  0.242553  0.183533  0.136364  0.163043
4     0.204900  0.178138  0.205660  0.193617  0.123499  0.164773  0.169565
...        ...       ...       ...       ...       ...       ...       ...
8347  0.224944  0.216599  0.233962  0.242553  0.192110  0.172348  0.219565
8348  0.187082  0.125506  0.183019  0.229787  0.180103  0.193182  0.252174
8349  0.262806  0.218623  0.273585  0.246809  0.176672  0.147727  0.206522
8350  0.231626  0.224696  0.215094  0.217021  0.178388  0.151515  0.215217
8351  0.189310  0.161943  0.177358  0.212766  0.162950  0.181818  0.247826

[8352 rows x 7 columns]

In [7]:
date_range = pd.date_range('2019-11-03 00:00', '2019-12-01 23:59', freq='5Min')
myser = pd.Series(data=date_range, name='Timestamp')

In [8]:
len(myser)

8352

In [9]:
df.drop(columns = ['f1', 'f2', 'f3', 'f4', 'f6', 'f7'], inplace=True);
df['Timestamp'] = myser

# Re-arrange spatial columns, so, the data is sequential
df = df[['Timestamp','f5']]

In [10]:
df

Timestamp        f5
0    2019-11-03 00:00:00  0.156089
1    2019-11-03 00:05:00  0.209262
2    2019-11-03 00:10:00  0.185249
3    2019-11-03 00:15:00  0.183533
4    2019-11-03 00:20:00  0.123499
...                  ...       ...
8347 2019-12-01 23:35:00  0.192110
8348 2019-12-01 23:40:00  0.180103
8349 2019-12-01 23:45:00  0.176672
8350 2019-12-01 23:50:00  0.178388
8351 2019-12-01 23:55:00  0.162950

[8352 rows x 2 columns]

In [11]:
df.iloc[4320]          # First sample

Timestamp    2019-11-18 00:00:00
f5                      0.070326
Name: 4320, dtype: object

In [12]:
df.iloc[2304]          # -1 week (-2016 samples)

Timestamp    2019-11-11 00:00:00
f5                      0.125214
Name: 2304, dtype: object

In [13]:
df.iloc[288]           # -2 week (-4032 samples)

Timestamp    2019-11-04 00:00:00
f5                      0.102916
Name: 288, dtype: object

# Generate Weekly Samples

In [14]:
a = np.zeros((2, 7))
b = np.zeros((2, 7))
x = 4320                           # Start

for i in range(len(df.iloc[x:])):
    for j in range(2):
        for k in range(7):
            if j == 0:
                a[j][k] = df.iloc[x-2019+i+k].drop(['Timestamp'])
            else:
                a[j][k] = df.iloc[x-4035+i+k].drop(['Timestamp'])
    b = np.append(b, a, axis=0)

b = np.delete(b, np.s_[0:2], 0).reshape(-1, 2, 7)

In [15]:
b[0]

array([[0.13379074, 0.12864494, 0.11492281, 0.12521441, 0.10634648,
        0.12521441, 0.10291595],
       [0.15780446, 0.10291595, 0.10977702, 0.10291595, 0.08404803,
        0.09777015, 0.11149228]])

In [16]:
b[1]

array([[0.12864494, 0.11492281, 0.12521441, 0.10634648, 0.12521441,
        0.10291595, 0.10634648],
       [0.10291595, 0.10977702, 0.10291595, 0.08404803, 0.09777015,
        0.11149228, 0.07375643]])

In [17]:
b[0].flatten()

array([0.13379074, 0.12864494, 0.11492281, 0.12521441, 0.10634648,
       0.12521441, 0.10291595, 0.15780446, 0.10291595, 0.10977702,
       0.10291595, 0.08404803, 0.09777015, 0.11149228])

In [18]:
a = b.flatten().reshape(-1,14)

In [19]:
a[0]

array([0.13379074, 0.12864494, 0.11492281, 0.12521441, 0.10634648,
       0.12521441, 0.10291595, 0.15780446, 0.10291595, 0.10977702,
       0.10291595, 0.08404803, 0.09777015, 0.11149228])

#### Confirmation

In [20]:
a[0]

array([0.13379074, 0.12864494, 0.11492281, 0.12521441, 0.10634648,
       0.12521441, 0.10291595, 0.15780446, 0.10291595, 0.10977702,
       0.10291595, 0.08404803, 0.09777015, 0.11149228])

In [21]:
df.iloc[2304] 

Timestamp    2019-11-11 00:00:00
f5                      0.125214
Name: 2304, dtype: object

In [22]:
df.iloc[288] 

Timestamp    2019-11-04 00:00:00
f5                      0.102916
Name: 288, dtype: object

In [23]:
len(a)

4032

# Save Data

In [24]:
joblib.dump(a, "002weeks_test_Nov.save"); 