In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#### Read training data from csv files

In [2]:
Train     = pd.read_csv('01train_scaled.csv', index_col=0, parse_dates=[8])
Test      = pd.read_csv('01test_scaled.csv', index_col=0, parse_dates=[8])

In [3]:
Test

f1        f2        f3        f4        f5        f6        f7  \
0     0.289532  0.277328  0.226415  0.259574  0.204117  0.147727  0.150000   
1     0.258352  0.230769  0.277358  0.231915  0.198971  0.168561  0.160870   
2     0.211581  0.208502  0.232075  0.242553  0.202401  0.195076  0.213043   
3     0.242762  0.232794  0.213208  0.221277  0.176672  0.178030  0.195652   
4     0.238307  0.226721  0.235849  0.253191  0.192110  0.126894  0.128261   
...        ...       ...       ...       ...       ...       ...       ...   
4027  0.282851  0.253036  0.264151  0.302128  0.233276  0.196970  0.169565   
4028  0.262806  0.222672  0.243396  0.246809  0.166381  0.174242  0.180435   
4029  0.204900  0.188259  0.213208  0.270213  0.221269  0.166667  0.171739   
4030  0.273942  0.246964  0.247170  0.219149  0.183533  0.195076  0.193478   
4031  0.247216  0.194332  0.237736  0.272340  0.193825  0.178030  0.200000   

               Timestamp  
0    2019-06-03 00:00:00  
1    2019-06-03 00:05:00  
2    2019-06-03 00:10:00  
3    2019-06-03 00:15:00  
4    2019-06-03 00:20:00  
...                  ...  
4027 2019-06-16 23:35:00  
4028 2019-06-16 23:40:00  
4029 2019-06-16 23:45:00  
4030 2019-06-16 23:50:00  
4031 2019-06-16 23:55:00  

[4032 rows x 8 columns]

In [4]:
type(Test.iloc[0]['Timestamp'])

pandas._libs.tslibs.timestamps.Timestamp

In [5]:
train = Train.drop('Timestamp', axis=1)
test = Test.drop('Timestamp', axis=1)

In [6]:
train

f1        f2        f3        f4        f5        f6        f7
0      0.200445  0.161943  0.230189  0.265957  0.190395  0.060606  0.084783
1      0.191537  0.155870  0.235849  0.265957  0.174957  0.125000  0.154348
2      0.213808  0.214575  0.230189  0.238298  0.173242  0.126894  0.145652
3      0.213808  0.170040  0.175472  0.212766  0.152659  0.155303  0.182609
4      0.193764  0.161943  0.201887  0.242553  0.157804  0.113636  0.121739
...         ...       ...       ...       ...       ...       ...       ...
31099  0.298441  0.253036  0.288679  0.291489  0.255575  0.204545  0.184783
31100  0.407572  0.382591  0.358491  0.312766  0.286449  0.195076  0.191304
31101  0.276169  0.285425  0.309434  0.293617  0.257290  0.231061  0.247826
31102  0.271715  0.246964  0.335849  0.270213  0.217839  0.159091  0.173913
31103  0.229399  0.212551  0.245283  0.265957  0.222985  0.176136  0.189130

[31104 rows x 7 columns]

# 5-minute (1 step ahead) foreast

## Train

In [7]:
length = 15
step = 1
k = -1

a = np.zeros((15, 7))
b = np.zeros((7,))
x = np.zeros((15, 7))
y = np.zeros((7,))


for i in range(length, (len(train)-step+1)):
    b = np.asarray(train.iloc[i+step-1])
    k = k+1
    for j in range(length):
        if j+k <= (len(train) + length - step):
            a[j] = train.iloc[j+k]
            
    x = np.append(x, a, axis=0)
    y = np.append(y, b, axis=0)
    
x = np.delete(x, np.s_[0:15], 0).reshape(-1, 15, 7)
y = np.delete(y, np.s_[0:7], 0).reshape(-1, 7)

In [8]:
x.shape

(31089, 15, 7)

In [9]:
y.shape

(31089, 7)

In [10]:
train.tail(16)

f1        f2        f3        f4        f5        f6        f7
31088  0.483296  0.417004  0.390566  0.463830  0.421955  0.257576  0.282609
31089  0.374165  0.366397  0.339623  0.351064  0.308748  0.333333  0.319565
31090  0.489978  0.443320  0.445283  0.414894  0.387650  0.304924  0.276087
31091  0.416481  0.410931  0.433962  0.376596  0.346484  0.337121  0.336957
31092  0.383073  0.392713  0.373585  0.363830  0.336192  0.284091  0.276087
31093  0.351893  0.319838  0.341509  0.334043  0.300172  0.231061  0.267391
31094  0.280624  0.329960  0.318868  0.291489  0.252144  0.225379  0.230435
31095  0.298441  0.295547  0.316981  0.370213  0.336192  0.251894  0.263043
31096  0.378619  0.334008  0.339623  0.325532  0.295026  0.214015  0.226087
31097  0.293987  0.269231  0.301887  0.291489  0.253859  0.232955  0.239130
31098  0.298441  0.238866  0.283019  0.280851  0.238422  0.195076  0.197826
31099  0.298441  0.253036  0.288679  0.291489  0.255575  0.204545  0.184783
31100  0.407572  0.382591  0.358491  0.312766  0.286449  0.195076  0.191304
31101  0.276169  0.285425  0.309434  0.293617  0.257290  0.231061  0.247826
31102  0.271715  0.246964  0.335849  0.270213  0.217839  0.159091  0.173913
31103  0.229399  0.212551  0.245283  0.265957  0.222985  0.176136  0.189130

In [11]:
y[-1]

array([0.22939866, 0.21255061, 0.24528302, 0.26595745, 0.22298456,
       0.17613636, 0.18913043])

In [12]:
# Checked as correct

In [13]:
# Save 

np.savez_compressed("Deep_train_5_multi", x=x , y=y)

## Test

In [14]:
length = 15
step = 1
k = -1

a = np.zeros((15, 7))
b = np.zeros((7,))
x = np.zeros((15, 7))
y = np.zeros((7,))


for i in range(length, (len(test)-step+1)):
    b = np.asarray(test.iloc[i+step-1])
    k = k+1
    for j in range(length):
        if j+k <= (len(test) + length - step):
            a[j] = test.iloc[j+k]
            
    x = np.append(x, a, axis=0)
    y = np.append(y, b, axis=0)
    
x = np.delete(x, np.s_[0:15], 0).reshape(-1, 15, 7)
y = np.delete(y, np.s_[0:7], 0).reshape(-1, 7)

In [15]:
x.shape

(4017, 15, 7)

In [16]:
y.shape

(4017, 7)

In [56]:
test.tail()

f1        f2        f3        f4        f5        f6        f7
4027  0.282851  0.253036  0.264151  0.302128  0.233276  0.196970  0.169565
4028  0.262806  0.222672  0.243396  0.246809  0.166381  0.174242  0.180435
4029  0.204900  0.188259  0.213208  0.270213  0.221269  0.166667  0.171739
4030  0.273942  0.246964  0.247170  0.219149  0.183533  0.195076  0.193478
4031  0.247216  0.194332  0.237736  0.272340  0.193825  0.178030  0.200000

In [17]:
y[-1]

array([0.24721604, 0.19433198, 0.23773585, 0.27234043, 0.19382504,
       0.1780303 , 0.2       ])

In [18]:
# Checked as correct

In [19]:
# Save 

np.savez_compressed("Deep_test_5_multi", x=x , y=y)

# 15-minute (3 step ahead) forecast

## Train

In [20]:
length = 15
step = 3
k = -1

a = np.zeros((15, 7))
b = np.zeros((7,))
x = np.zeros((15, 7))
y = np.zeros((7,))


for i in range(length, (len(train)-step+1)):
    b = np.asarray(train.iloc[i+step-1])
    k = k+1
    for j in range(length):
        if j+k <= (len(train) + length - step):
            a[j] = train.iloc[j+k]
            
    x = np.append(x, a, axis=0)
    y = np.append(y, b, axis=0)
    
x = np.delete(x, np.s_[0:15], 0).reshape(-1, 15, 7)
y = np.delete(y, np.s_[0:7], 0).reshape(-1, 7)

In [21]:
x.shape

(31087, 15, 7)

In [22]:
y.shape

(31087, 7)

In [57]:
train.tail(16)

f1        f2        f3        f4        f5        f6        f7
31088  0.483296  0.417004  0.390566  0.463830  0.421955  0.257576  0.282609
31089  0.374165  0.366397  0.339623  0.351064  0.308748  0.333333  0.319565
31090  0.489978  0.443320  0.445283  0.414894  0.387650  0.304924  0.276087
31091  0.416481  0.410931  0.433962  0.376596  0.346484  0.337121  0.336957
31092  0.383073  0.392713  0.373585  0.363830  0.336192  0.284091  0.276087
31093  0.351893  0.319838  0.341509  0.334043  0.300172  0.231061  0.267391
31094  0.280624  0.329960  0.318868  0.291489  0.252144  0.225379  0.230435
31095  0.298441  0.295547  0.316981  0.370213  0.336192  0.251894  0.263043
31096  0.378619  0.334008  0.339623  0.325532  0.295026  0.214015  0.226087
31097  0.293987  0.269231  0.301887  0.291489  0.253859  0.232955  0.239130
31098  0.298441  0.238866  0.283019  0.280851  0.238422  0.195076  0.197826
31099  0.298441  0.253036  0.288679  0.291489  0.255575  0.204545  0.184783
31100  0.407572  0.382591  0.358491  0.312766  0.286449  0.195076  0.191304
31101  0.276169  0.285425  0.309434  0.293617  0.257290  0.231061  0.247826
31102  0.271715  0.246964  0.335849  0.270213  0.217839  0.159091  0.173913
31103  0.229399  0.212551  0.245283  0.265957  0.222985  0.176136  0.189130

In [23]:
y[-1]

array([0.22939866, 0.21255061, 0.24528302, 0.26595745, 0.22298456,
       0.17613636, 0.18913043])

In [24]:
# Checked as correct

In [25]:
# Save 

np.savez_compressed("Deep_train_15_multi", x=x , y=y)

## Test

In [26]:
length = 15
step = 3
k = -1

a = np.zeros((15, 7))
b = np.zeros((7,))
x = np.zeros((15, 7))
y = np.zeros((7,))


for i in range(length, (len(test)-step+1)):
    b = np.asarray(test.iloc[i+step-1])
    k = k+1
    for j in range(length):
        if j+k <= (len(test) + length - step):
            a[j] = test.iloc[j+k]
            
    x = np.append(x, a, axis=0)
    y = np.append(y, b, axis=0)
    
x = np.delete(x, np.s_[0:15], 0).reshape(-1, 15, 7)
y = np.delete(y, np.s_[0:7], 0).reshape(-1, 7)

In [27]:
x.shape

(4015, 15, 7)

In [28]:
y.shape

(4015, 7)

In [58]:
test.tail()

f1        f2        f3        f4        f5        f6        f7
4027  0.282851  0.253036  0.264151  0.302128  0.233276  0.196970  0.169565
4028  0.262806  0.222672  0.243396  0.246809  0.166381  0.174242  0.180435
4029  0.204900  0.188259  0.213208  0.270213  0.221269  0.166667  0.171739
4030  0.273942  0.246964  0.247170  0.219149  0.183533  0.195076  0.193478
4031  0.247216  0.194332  0.237736  0.272340  0.193825  0.178030  0.200000

In [29]:
y[-1]

array([0.24721604, 0.19433198, 0.23773585, 0.27234043, 0.19382504,
       0.1780303 , 0.2       ])

In [30]:
# Checked as correct

In [31]:
# Save 

np.savez_compressed("Deep_test_15_multi", x=x , y=y)

# 30-minute (6 step ahead) forecast

## Train

In [32]:
length = 15
step = 6
k = -1

a = np.zeros((15, 7))
b = np.zeros((7,))
x = np.zeros((15, 7))
y = np.zeros((7,))


for i in range(length, (len(train)-step+1)):
    b = np.asarray(train.iloc[i+step-1])
    k = k+1
    for j in range(length):
        if j+k <= (len(train) + length - step):
            a[j] = train.iloc[j+k]
            
    x = np.append(x, a, axis=0)
    y = np.append(y, b, axis=0)
    
x = np.delete(x, np.s_[0:15], 0).reshape(-1, 15, 7)
y = np.delete(y, np.s_[0:7], 0).reshape(-1, 7)

In [33]:
x.shape

(31084, 15, 7)

In [34]:
y.shape

(31084, 7)

In [59]:
train.tail()

f1        f2        f3        f4        f5        f6        f7
31099  0.298441  0.253036  0.288679  0.291489  0.255575  0.204545  0.184783
31100  0.407572  0.382591  0.358491  0.312766  0.286449  0.195076  0.191304
31101  0.276169  0.285425  0.309434  0.293617  0.257290  0.231061  0.247826
31102  0.271715  0.246964  0.335849  0.270213  0.217839  0.159091  0.173913
31103  0.229399  0.212551  0.245283  0.265957  0.222985  0.176136  0.189130

In [35]:
y[-1]

array([0.22939866, 0.21255061, 0.24528302, 0.26595745, 0.22298456,
       0.17613636, 0.18913043])

In [36]:
# Checked as correct

In [37]:
# Save 

np.savez_compressed("Deep_train_30_multi", x=x , y=y)

## Test

In [38]:
length = 15
step = 6
k = -1

a = np.zeros((15, 7))
b = np.zeros((7,))
x = np.zeros((15, 7))
y = np.zeros((7,))


for i in range(length, (len(test)-step+1)):
    b = np.asarray(test.iloc[i+step-1])
    k = k+1
    for j in range(length):
        if j+k <= (len(test) + length - step):
            a[j] = test.iloc[j+k]
            
    x = np.append(x, a, axis=0)
    y = np.append(y, b, axis=0)
    
x = np.delete(x, np.s_[0:15], 0).reshape(-1, 15, 7)
y = np.delete(y, np.s_[0:7], 0).reshape(-1, 7)

In [39]:
x.shape

(4012, 15, 7)

In [40]:
y.shape

(4012, 7)

In [60]:
test.tail()

f1        f2        f3        f4        f5        f6        f7
4027  0.282851  0.253036  0.264151  0.302128  0.233276  0.196970  0.169565
4028  0.262806  0.222672  0.243396  0.246809  0.166381  0.174242  0.180435
4029  0.204900  0.188259  0.213208  0.270213  0.221269  0.166667  0.171739
4030  0.273942  0.246964  0.247170  0.219149  0.183533  0.195076  0.193478
4031  0.247216  0.194332  0.237736  0.272340  0.193825  0.178030  0.200000

In [41]:
y[-1]

array([0.24721604, 0.19433198, 0.23773585, 0.27234043, 0.19382504,
       0.1780303 , 0.2       ])

In [42]:
# Checked as correct

In [43]:
# Save 

np.savez_compressed("Deep_test_30_multi", x=x , y=y)

# 60-minute (12 step ahead) forecast

## Train

In [44]:
length = 15
step = 12
k = -1

a = np.zeros((15, 7))
b = np.zeros((7,))
x = np.zeros((15, 7))
y = np.zeros((7,))


for i in range(length, (len(train)-step+1)):
    b = np.asarray(train.iloc[i+step-1])
    k = k+1
    for j in range(length):
        if j+k <= (len(train) + length - step):
            a[j] = train.iloc[j+k]
            
    x = np.append(x, a, axis=0)
    y = np.append(y, b, axis=0)
    
x = np.delete(x, np.s_[0:15], 0).reshape(-1, 15, 7)
y = np.delete(y, np.s_[0:7], 0).reshape(-1, 7)

In [45]:
x.shape

(31078, 15, 7)

In [46]:
y.shape

(31078, 7)

In [61]:
train.tail()

f1        f2        f3        f4        f5        f6        f7
31099  0.298441  0.253036  0.288679  0.291489  0.255575  0.204545  0.184783
31100  0.407572  0.382591  0.358491  0.312766  0.286449  0.195076  0.191304
31101  0.276169  0.285425  0.309434  0.293617  0.257290  0.231061  0.247826
31102  0.271715  0.246964  0.335849  0.270213  0.217839  0.159091  0.173913
31103  0.229399  0.212551  0.245283  0.265957  0.222985  0.176136  0.189130

In [47]:
y[-1]

array([0.22939866, 0.21255061, 0.24528302, 0.26595745, 0.22298456,
       0.17613636, 0.18913043])

In [48]:
# Checked as correct

In [49]:
# Save 

np.savez_compressed("Deep_train_60_multi", x=x , y=y)

## Test

In [50]:
length = 15
step = 12
k = -1

a = np.zeros((15, 7))
b = np.zeros((7,))
x = np.zeros((15, 7))
y = np.zeros((7,))


for i in range(length, (len(test)-step+1)):
    b = np.asarray(test.iloc[i+step-1])
    k = k+1
    for j in range(length):
        if j+k <= (len(test) + length - step):
            a[j] = test.iloc[j+k]
            
    x = np.append(x, a, axis=0)
    y = np.append(y, b, axis=0)
    
x = np.delete(x, np.s_[0:15], 0).reshape(-1, 15, 7)
y = np.delete(y, np.s_[0:7], 0).reshape(-1, 7)

In [51]:
x.shape

(4006, 15, 7)

In [52]:
y.shape

(4006, 7)

In [62]:
test.tail()

f1        f2        f3        f4        f5        f6        f7
4027  0.282851  0.253036  0.264151  0.302128  0.233276  0.196970  0.169565
4028  0.262806  0.222672  0.243396  0.246809  0.166381  0.174242  0.180435
4029  0.204900  0.188259  0.213208  0.270213  0.221269  0.166667  0.171739
4030  0.273942  0.246964  0.247170  0.219149  0.183533  0.195076  0.193478
4031  0.247216  0.194332  0.237736  0.272340  0.193825  0.178030  0.200000

In [53]:
y[-1]

array([0.24721604, 0.19433198, 0.23773585, 0.27234043, 0.19382504,
       0.1780303 , 0.2       ])

In [54]:
# Checked as correct

In [55]:
# Save 

np.savez_compressed("Deep_test_60_multi", x=x , y=y)