In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import joblib

In [2]:
# General Period
train_period = joblib.load("00Periodicity_train.save") 
test_period = joblib.load("00Periodicity_test.save") 

# 2 Week priodicity
train_2week = joblib.load("002weeks_train.save") 
test_2week = joblib.load("002weeks_test.save") 

In [3]:
train_period.shape

(31104, 49)

In [4]:
train_2week.shape

(31104, 14)

In [5]:
test_period.shape

(4032, 49)

In [6]:
test_2week.shape

(4032, 14)

In [7]:
train_period[0]

array([0.19291023, 0.03761239, 0.13036021, 0.26072041, 0.16638079,
       0.19039451, 0.2186964 , 0.18536306, 0.03597076, 0.12692967,
       0.24528302, 0.16037736, 0.18010292, 0.20754717, 0.17232704,
       0.02996191, 0.10634648, 0.23327616, 0.16209262, 0.17152659,
       0.18524871, 0.1745283 , 0.01995909, 0.14236707, 0.21955403,
       0.16380789, 0.17495712, 0.1796741 , 0.18278302, 0.02931696,
       0.12349914, 0.23156089, 0.16252144, 0.18181818, 0.20368782,
       0.18181818, 0.02484867, 0.12692967, 0.2212693 , 0.17024014,
       0.18524871, 0.19682676, 0.1745283 , 0.01956205, 0.1406518 ,
       0.21269297, 0.16252144, 0.17066895, 0.18310463])

In [8]:
train_2week[0]

array([0.135506  , 0.1457976 , 0.18867925, 0.16466552, 0.16638079,
       0.15608919, 0.18010292, 0.16638079, 0.15951973, 0.18181818,
       0.15780446, 0.12864494, 0.15437393, 0.18353345])

In [9]:
np.concatenate((train_period[0], train_2week[0]), axis=0)

array([0.19291023, 0.03761239, 0.13036021, 0.26072041, 0.16638079,
       0.19039451, 0.2186964 , 0.18536306, 0.03597076, 0.12692967,
       0.24528302, 0.16037736, 0.18010292, 0.20754717, 0.17232704,
       0.02996191, 0.10634648, 0.23327616, 0.16209262, 0.17152659,
       0.18524871, 0.1745283 , 0.01995909, 0.14236707, 0.21955403,
       0.16380789, 0.17495712, 0.1796741 , 0.18278302, 0.02931696,
       0.12349914, 0.23156089, 0.16252144, 0.18181818, 0.20368782,
       0.18181818, 0.02484867, 0.12692967, 0.2212693 , 0.17024014,
       0.18524871, 0.19682676, 0.1745283 , 0.01956205, 0.1406518 ,
       0.21269297, 0.16252144, 0.17066895, 0.18310463, 0.135506  ,
       0.1457976 , 0.18867925, 0.16466552, 0.16638079, 0.15608919,
       0.18010292, 0.16638079, 0.15951973, 0.18181818, 0.15780446,
       0.12864494, 0.15437393, 0.18353345])

### Train

In [10]:
b = np.zeros(63)

for i in range(len(train_period)):
    a = np.concatenate((train_period[i], train_2week[i]), axis=0)
    b = np.append(b, a, axis=0)

b = b.reshape(-1,63)
Xtrain = np.delete(b, np.s_[0], 0)

In [11]:
Xtrain[0] == np.concatenate((train_period[0], train_2week[0]), axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [12]:
Xtrain.shape

(31104, 63)

### Test

In [13]:
b = np.zeros(63)

for i in range(len(test_period)):
    a = np.concatenate((test_period[i], test_2week[i]), axis=0)
    b = np.append(b, a, axis=0)
    
b = b.reshape(-1,63)
Xtest = np.delete(b, np.s_[0], 0)

In [14]:
Xtest[0] == np.concatenate((test_period[0], test_2week[0]), axis=0)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True])

In [15]:
Xtest.shape

(4032, 63)

# Samples

### 5 mins

In [16]:
# Delete first 15 samples
a = np.delete(Xtrain, np.s_[0:15], 0)
b = np.delete(Xtest, np.s_[0:15], 0)

In [17]:
len(a)

31089

In [18]:
len(b)

4017

In [19]:
# Save 

np.save("Wide_train_5", a)
np.save("Wide_test_5", b)

### 15 mins

In [20]:
# Delete first 17 samples
a = np.delete(Xtrain, np.s_[0:17], 0)
b = np.delete(Xtest, np.s_[0:17], 0)

In [21]:
len(a)

31087

In [22]:
len(b)

4015

In [23]:
# Save 

np.save("Wide_train_15", a)
np.save("Wide_test_15", b)

### 30 mins

In [24]:
# Delete first 20 samples
a = np.delete(Xtrain, np.s_[0:20], 0)
b = np.delete(Xtest, np.s_[0:20], 0)

In [25]:
len(a)

31084

In [26]:
len(b)

4012

In [27]:
# Save 

np.save("Wide_train_30", a)
np.save("Wide_test_30", b)

### 60 mins

In [28]:
# Delete first 27 samples
a = np.delete(Xtrain, np.s_[0:26], 0)
b = np.delete(Xtest, np.s_[0:26], 0)

In [29]:
len(a)

31078

In [30]:
len(b)

4006

In [31]:
# Save 

np.save("Wide_train_60", a)
np.save("Wide_test_60", b)